// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using wikiAPI.Repositories;

#nullable disable

namespace wikiAPI.Migrations
{
    [DbContext(typeof(WikiDbContext))]
    [Migration("20250425134726_Try-PostgreSQL")]
    partial class TryPostgreSQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("wikiAPI.Models.WikiCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("WikiCategories");
                });

            modelBuilder.Entity("wikiAPI.Models.WikiEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WikiCategoryID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("WikiCategoryID");

                    b.ToTable("WikiEntries");
                });

            modelBuilder.Entity("wikiAPI.Models.WikiSection", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.PrimitiveCollection<List<string>>("Bodies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WikiEntryID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("WikiEntryID");

                    b.ToTable("WikiSections");
                });

            modelBuilder.Entity("wikiAPI.Models.WikiStat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Val")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WikiEntryID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("WikiEntryID");

                    b.ToTable("WikiStats");
                });

            modelBuilder.Entity("wikiAPI.Models.WikiEntry", b =>
                {
                    b.HasOne("wikiAPI.Models.WikiCategory", "WikiCategory")
                        .WithMany("WikiEntries")
                        .HasForeignKey("WikiCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WikiCategory");
                });

            modelBuilder.Entity("wikiAPI.Models.WikiSection", b =>
                {
                    b.HasOne("wikiAPI.Models.WikiEntry", null)
                        .WithMany("Sections")
                        .HasForeignKey("WikiEntryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("wikiAPI.Models.WikiStat", b =>
                {
                    b.HasOne("wikiAPI.Models.WikiEntry", null)
                        .WithMany("Stats")
                        .HasForeignKey("WikiEntryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("wikiAPI.Models.WikiCategory", b =>
                {
                    b.Navigation("WikiEntries");
                });

            modelBuilder.Entity("wikiAPI.Models.WikiEntry", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
